version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x"
  max_line_length = 100

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[exclude_patterns]
patterns = [
  "**/bak/**",
  "**/public/libav/**",
  "**/public/ffmpeg-core/**",
  "**/node_modules/**",
  "**/dist/**",
  "scripts/**"
]

[test_patterns]
patterns = [
  "**/tests/**",
  "**/*.test.ts",
  "**/*.test.js"
]
