version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.10"
  max_line_length = 110
  skip_doc_coverage = ["magic_methods", "init", "test"]

[[analyzers]]
name = "javascript"
enabled = true
...
  [analyzers.meta]
  environment = ["nodejs", "browser"]
  dialect = "typescript"
  plugins = ["react"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[exclude_patterns]
patterns = [
  "**/bak/**",
  "**/public/libav/**",
  "**/public/ffmpeg-core/**",
  "**/node_modules/**",
  "**/dist/**",
  "**/temp/**",
  "**/temp_refs/**",
  "scripts/**",
  "BTC-ISMIR19/**",
  "mobile/**"
]

[test_patterns]
patterns = [
  "**/tests/**",
  "**/*.test.ts",
  "**/*.test.js"
]
